# Generated by Django 6.0.1 on 2026-02-02 22:45

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('rbac', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='membership',
            name='unique_membership',
        ),
        migrations.AlterUniqueTogether(
            name='membership',
            unique_together={('user', 'role')},
        ),
        migrations.AlterField(
            model_name='auditentry',
            name='timestamp',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2026, 2, 2, 22, 45, 4, 261035, tzinfo=datetime.timezone.utc)),
        ),
        migrations.RemoveField(
            model_name='role',
            name='permissions',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='object_id',
        ),
        migrations.AddField(
            model_name='role',
            name='permissions',
            field=models.ManyToManyField(blank=True, related_name='rbac_roles', to='auth.permission'),
        ),
    ]
