# Generated by Django 6.0.1 on 2026-04-30 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditentry',
            name='action',
            field=models.CharField(choices=[('create', 'create'), ('edit', 'edit'), ('delete', 'delete'), ('notification', 'notification')], max_length=20),
        ),
    ]
