# Generated by Django 6.0.1 on 2026-02-08 03:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0002_remove_membership_unique_membership_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditentry',
            name='timestamp',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2026, 2, 8, 3, 17, 7, 287795, tzinfo=datetime.timezone.utc)),
        ),
    ]
